version: '3'

dotenv: ['.env', '.env.test']

vars:
  LOCAL_SERVICES: "app mongo"
  COMPOSE_FILE: "COMPOSE_FILE=docker-compose.yml"
  BUILD_CMD: "docker-compose build --no-cache"
  RUN_CMD: "docker-compose up -d {{.LOCAL_SERVICES}}"
  STOP_CMD: "docker-compose down -v"
  TEST_CMD: "docker-compose exec -T app yarn test:e2e"
  BASH_CMD: "docker exec -it app-$PROJECT_NAME sh"
  INSTALL_DEPENDENCIES_CMD: "docker-compose run app yarn install --ignore-scripts"
  LOGS_CMD: "docker-compose logs -f --tail=500"
  LOGS_APP_CMD: "docker-compose logs -f --tail=500 app"

tasks:
  default:
    cmds:
      - task: run

  run:
    desc: Execute local project
    cmds:
      - task: build
      - '{{.RUN_CMD}}'

  build:
    desc: Build container
    cmds:
      - '{{.BUILD_CMD}}'

  install:
    desc: Install dependencies
    cmds:
      - task: stop
      - task: build
      - '{{.INSTALL_DEPENDENCIES_CMD}}'

  stop:
    desc: Stop env
    cmds:
      - '{{.STOP_CMD}}'

  restart:
    desc: Recreate env
    cmds:
      - task: stop
      - task: run

  test:
    desc: Execute tests
    cmds:
      - task: stop
      - task: run
      - '{{.TEST_CMD}}'
      - task: stop
  app:
    desc: Enter app bash
    cmds:
      - '{{.BASH_CMD}}'  

  logs:
    desc: Docker logs
    cmds:
      - '{{.LOGS_CMD}}'   

  logs:app:
    desc: Docker app logs
    cmds:
      - '{{.LOGS_APP_CMD}}'  
